# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('domicilio', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
