# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('proveedor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor')),
            ],
        ),
    ]
