# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_auto_20170330_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='proveedor',
            new_name='rfc',
        ),
    ]
