# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_auto_20170330_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=20)),
                ('cantidad', models.CharField(max_length=20)),
                ('unidad', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Contrato')),
            ],
        ),
    ]
